// Ported verbatim from @dazl/dev (MIT, Copyright (c) 2025 Dazl).
// See LICENSE for attribution.
//
// This file is the single load-bearing primitive of the whole editor: it
// populates `window.__propsToSource`, a WeakMap from every element's props
// object to `{ fileName, lineNumber, columnNumber }`. The preview-agent walks
// React fibers and looks up props in this map to go DOM-node → source line.
//
// DO NOT modify the Fragment key/children handling without understanding why:
// React 19 fragments only get fibers when they have a key, and a fragment
// fiber's `props` is the children array — so we coerce to an array and store
// the array as a WeakMap key so fragment sources are lookup-able too.

import * as ReactDevRuntime from 'react/jsx-dev-runtime';

const isBrowser = typeof window !== 'undefined';
const isObjectLike = (value: unknown): value is object => typeof value === 'object' && value !== null;

const generateKeyFromJSXSource = (source: ReactDevRuntime.JSXSource): string =>
  `Autogenerated(${source.fileName}:${source.lineNumber}:${source.columnNumber})`;

const propsToSource = new WeakMap<object, ReactDevRuntime.JSXSource>();

const jsxDEVKeepSource: typeof ReactDevRuntime.jsxDEV = (
  type,
  props,
  key,
  isStatic,
  source,
  self,
) => {
  const isFragmentWithSource = type === ReactDevRuntime.Fragment && source;
  if (isFragmentWithSource) {
    key = key === undefined ? generateKeyFromJSXSource(source) : key;
    if (isObjectLike(props) && 'children' in props) {
      if (!Array.isArray((props as { children: unknown }).children)) {
        props = { ...(props as object), children: [(props as { children: unknown }).children] };
        isStatic = true;
      }
      propsToSource.set((props as { children: unknown[] }).children, source);
    }
  }

  const reactElement = ReactDevRuntime.jsxDEV(type, props, key, isStatic, source, self);

  if (source && isObjectLike(reactElement.props)) {
    propsToSource.set(reactElement.props as object, source);
  }
  return reactElement;
};

if (isBrowser) {
  (window as Window).__propsToSource = propsToSource;
}

declare global {
  interface Window {
    __propsToSource: typeof propsToSource;
  }
}

export { Fragment, jsx, jsxs, type JSX } from 'react/jsx-runtime';
export { createElement } from 'react';
export const jsxDEV: typeof ReactDevRuntime.jsxDEV = isBrowser
  ? jsxDEVKeepSource
  : ReactDevRuntime.jsxDEV;
